version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: landchain-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 200528100634@Vn
      MYSQL_DATABASE: land_chain
      MYSQL_USER: landchain_app
      MYSQL_PASSWORD: E9GF4JmY091K8l3XJ9XotLNuPRwF3O3J
    ports:
      - "3000:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./modules/db/script.sql:/docker-entrypoint-initdb.d/script.sql

volumes:
  mysql-data: