POST http://localhost:9091/auth/users/register
Content-Type: application/json

{
  "first_name": "Roshan",
  "last_name": "Jayasinghe",
  "email": "roshan@gmail.com",
  "nic": "973456789V",
  "password": "Hiru2005@",
  "contact_no": "0768190976",
  "address": "Colombo",
  "sludi": "SL-UDI-000000008",
  "user_type": 4
}

HTTP/1.1 201  - Created
content-type: application/json
connection: close
server: ballerina
date: Thu, 24 Jul 2025 23:02:29 +0530
content-encoding: gzip
content-length: 79
###
POST http://localhost:9095/land/register
Authorization: Bearer eyJhbGciOiJSUzI1NiIsICJ0eXAiOiJKV1QifQ.eyJpc3MiOiJieXRlc2Vla2VycyIsICJhdWQiOiJMQU5EX09GRklDRVIiLCAiZXhwIjoxNzUzMzU3NzEwLCAibmJmIjoxNzUzMzU0MTEwLCAiaWF0IjoxNzUzMzU0MTEwfQ.cwpAOVn31X74lc_440Qk1EMxgfkCIrP_lQx7-4JBTo31ca_VcGdxfyTSHGtXvGY95hkqCDveO2VnpHNtJpVGlSCpo7ZgFVyDnwum-EePyO4dzEN0jnMfO-h1PZUGKnm9zZFirL-CfyHb4UMqD1Pvgru8aXk4VvGPKhZmP-_Klhne7fCbK9NJfYomfLTqk6-kuOo4NuXkx5llJspyfJgONK_oj_aqOxk0QCtgnIrBS__ZlqMXiQ-_nxQMzAcOsbp0u3LYP3V9HRAQ7a5_FpLIz3stobCHfdQUPavRR6RNz58b_iangMtWEyT_ecED7rCp3HcpJ_5ndHVnuINtcAczRA
Content-Type: application/json

{
  "landId": "234da",
  "landName": "Sample Land",
  "landPlace": "Colombo",
  "landLat": 0,
  "landLang": 0,
  "landSize": 10,
  "landValue": 0,
  "landType": "{?}",
  "registerDate": {
    "year": 2023,
    "month": 10,
    "day": 1
  },
  "landStatus": "REJECTED",
  "priority": 0
}

HTTP/1.1 401  - Unauthorized
content-type: text/plain
connection: close
server: ballerina
date: Thu, 24 Jul 2025 17:53:12 +0530
content-encoding: gzip
content-length: 62
###
POST http://localhost:9091/auth/users/login
Content-Type: application/json

{
  "email": "roshan@gmail.com",
  "password": "Hiru2005@",
  "user_type": 4
}

HTTP/1.1 200  - OK
content-type: application/json
connection: close
server: ballerina
date: Thu, 24 Jul 2025 23:02:49 +0530
content-encoding: gzip
content-length: 479
###
GET http://localhost:9095/land/getAllLands
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsICJ0eXAiOiJKV1QifQ.eyJpc3MiOiJieXRlc2Vla2VycyIsICJhdWQiOiJMQU5EX09GRklDRVIiLCAiZXhwIjoxNzUzMzYwODgxLCAibmJmIjoxNzUzMzU3MjgxLCAiaWF0IjoxNzUzMzU3MjgxfQ.flFVTk2MJazz9lD2cpBKUARu4rkkcSdSmUciwvUgAjo5Kseceicnjqsk0nBXGgj93YZgNmLLIA-9M5xzYjRvoRQ8_7tDmdvAoi7mvZwnEeDOP9FN6EEIOPbfLR5HK4frL4Bp-zHlnlA8u-TM095P4axckWKXU9_i9Ce7Lp6e8EdAFc6upz1jpx1WamO7dqt2FDguWT28wBGyy6KaDl_JFnS626yf45warLv0cO8VSOMJckzHZ45Xfy9sjpgufPrB852KnbnoZQbwnnOAvqx_OBsm63rB-LQH9-xvmqDERBBYem_Qt_LVLVHcbEkVztV0mCAqUhKfMArkjMzuWpgKRw

HTTP/1.1 200  - OK
content-type: application/json
connection: close
server: ballerina
date: Thu, 24 Jul 2025 17:53:13 +0530
content-encoding: gzip
content-length: 1211
###
GET http://localhost:9095/land/getLandById/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsICJ0eXAiOiJKV1QifQ.eyJpc3MiOiJieXRlc2Vla2VycyIsICJhdWQiOiJMQU5EX09GRklDRVIiLCAiZXhwIjoxNzUzMzYwODgxLCAibmJmIjoxNzUzMzU3MjgxLCAiaWF0IjoxNzUzMzU3MjgxfQ.flFVTk2MJazz9lD2cpBKUARu4rkkcSdSmUciwvUgAjo5Kseceicnjqsk0nBXGgj93YZgNmLLIA-9M5xzYjRvoRQ8_7tDmdvAoi7mvZwnEeDOP9FN6EEIOPbfLR5HK4frL4Bp-zHlnlA8u-TM095P4axckWKXU9_i9Ce7Lp6e8EdAFc6upz1jpx1WamO7dqt2FDguWT28wBGyy6KaDl_JFnS626yf45warLv0cO8VSOMJckzHZ45Xfy9sjpgufPrB852KnbnoZQbwnnOAvqx_OBsm63rB-LQH9-xvmqDERBBYem_Qt_LVLVHcbEkVztV0mCAqUhKfMArkjMzuWpgKRw

HTTP/1.1 200  - OK
content-type: application/json
connection: close
server: ballerina
date: Thu, 24 Jul 2025 17:53:13 +0530
content-encoding: gzip
content-length: 263
###
GET http://localhost:9095/land/getLegelOfficers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsICJ0eXAiOiJKV1QifQ.eyJpc3MiOiJieXRlc2Vla2VycyIsICJhdWQiOiJMQU5EX09GRklDRVIiLCAiZXhwIjoxNzUzMzYwODgxLCAibmJmIjoxNzUzMzU3MjgxLCAiaWF0IjoxNzUzMzU3MjgxfQ.flFVTk2MJazz9lD2cpBKUARu4rkkcSdSmUciwvUgAjo5Kseceicnjqsk0nBXGgj93YZgNmLLIA-9M5xzYjRvoRQ8_7tDmdvAoi7mvZwnEeDOP9FN6EEIOPbfLR5HK4frL4Bp-zHlnlA8u-TM095P4axckWKXU9_i9Ce7Lp6e8EdAFc6upz1jpx1WamO7dqt2FDguWT28wBGyy6KaDl_JFnS626yf45warLv0cO8VSOMJckzHZ45Xfy9sjpgufPrB852KnbnoZQbwnnOAvqx_OBsm63rB-LQH9-xvmqDERBBYem_Qt_LVLVHcbEkVztV0mCAqUhKfMArkjMzuWpgKRw

HTTP/1.1 200  - OK
content-type: application/json
connection: close
server: ballerina
date: Thu, 24 Jul 2025 17:53:14 +0530
content-encoding: gzip
content-length: 448
###
POST http://localhost:9098/land_owner/createDispute
Authorization: Bearer eyJhbGciOiJSUzI1NiIsICJ0eXAiOiJKV1QifQ.eyJpc3MiOiJieXRlc2Vla2VycyIsICJhdWQiOiJMQU5EX09XTkVSIiwgImV4cCI6MTc1MzM3OTQ1OSwgIm5iZiI6MTc1MzM3NTg1OSwgImlhdCI6MTc1MzM3NTg1OX0.Yh6O9m8SsZXt3dSa6zyL_1-VDzIJ9MQUwVJTumX3KpqXxv-pJDYZAWCcyqVwdrSS2t877_AlUo8iJXIAxa_mwf_pOQJoGcSgkB1BFqr-2YVd13ieCIVuDkSgQNFR16Egu_KxUjtdPTAdWJpiuDYl8JNb8JyljgOKf8Uv5ifLnymQHqLpwJr49dSmTK-SQSM0BYvtl9NMB6H2O4n8hM52LKNVIG9LNLG_1sdwWi82zcmJWeZ2jK2fYKJdmwP1YeN0FntZtaWIxXTiMMmB2pRYdLrZupI_s4qbJEmiESoiwL_7-SKSZ9uWQpkg9as0wqcRZNOXuOd8lZ80Pbp31gP4zQ
Content-Type: application/json

{
  "witnessName": "234da",
  "disputesDetails": "Sample Dispute",
  "landsId": 1,
  "legalOfficerId": 10
}

HTTP/1.1 404  - Not Found
content-type: application/json
connection: close
server: ballerina
date: Thu, 24 Jul 2025 23:06:21 +0530
content-encoding: gzip
content-length: 80
###
GET http://localhost:9092/legal_officer/getDisputes/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsICJ0eXAiOiJKV1QifQ.eyJpc3MiOiJieXRlc2Vla2VycyIsICJhdWQiOiJMRUdBTF9PRkZJQ0VSIiwgImV4cCI6MTc1MzM4MTk2OSwgIm5iZiI6MTc1MzM3ODM2OSwgImlhdCI6MTc1MzM3ODM2OX0.bfHY0X4Y1ZsqVRudC3OybjAZgdk1hwDAW6OFjEKsr87QdvpjUmBvyfB6RqdZqDBdzZDbDmeG692MX3vCF34H0HtXP0YXC_eY0-_fR1I-vygcIKVdVtqN8aMHgVtpy85ke-jxObI_QnrtIvRnSGJTdVwBR16C31dPSaaNFo2pGZKT2upVLsGz_GuKfty04P4Mbwhmo2SuDBHtiWC3tvcdbeDrdVcOLVDtz7mxAZxSrHv4suywuY-_M_4VhORY5NPBKIY_dcXe2lbnIoEkE09XR2Y4dBbqEIGdp6OqrkWKLww7Yx39TiJggLnfkUZ9HM1kh3wXWyAzxL5Ghv4tl1yFzw

HTTP/1.1 200  - OK
content-type: application/json
connection: close
server: ballerina
date: Thu, 24 Jul 2025 23:06:42 +0530
content-encoding: gzip
content-length: 235
###
POST http://localhost:9092/legal_officer/addEstimateTime
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsICJ0eXAiOiJKV1QifQ.eyJpc3MiOiJieXRlc2Vla2VycyIsICJhdWQiOiJMRUdBTF9PRkZJQ0VSIiwgImV4cCI6MTc1MzM4MTk2OSwgIm5iZiI6MTc1MzM3ODM2OSwgImlhdCI6MTc1MzM3ODM2OX0.bfHY0X4Y1ZsqVRudC3OybjAZgdk1hwDAW6OFjEKsr87QdvpjUmBvyfB6RqdZqDBdzZDbDmeG692MX3vCF34H0HtXP0YXC_eY0-_fR1I-vygcIKVdVtqN8aMHgVtpy85ke-jxObI_QnrtIvRnSGJTdVwBR16C31dPSaaNFo2pGZKT2upVLsGz_GuKfty04P4Mbwhmo2SuDBHtiWC3tvcdbeDrdVcOLVDtz7mxAZxSrHv4suywuY-_M_4VhORY5NPBKIY_dcXe2lbnIoEkE09XR2Y4dBbqEIGdp6OqrkWKLww7Yx39TiJggLnfkUZ9HM1kh3wXWyAzxL5Ghv4tl1yFzw
{
    "caseId": "CASE-17310792338",
    "estimateTime":"2 weeks"
}

HTTP/1.1 200  - OK
content-type: application/json
connection: close
server: ballerina
date: Thu, 24 Jul 2025 23:58:47 +0530
content-encoding: gzip
content-length: 99